services:
    app:
        image: node:20-alpine
        volumes:
            - .:/app
        working_dir: /app
        command: npm run start:dev
        ports:
            - 3000:3000
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASS: password
            DB_NAME: postgres
    db:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
